name: tag-parser

on:
    push:

jobs:
    tag-parser:
        name: Tag Parser
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo
              uses: actions/checkout@v4
            - name: Build
              run: |-
                  cd .github/actions/tag-parser
                  npm ci
                  npm run build
            - name: Parse solutions
              uses: ./.github/actions/tag-parser
            - run: git remote set-url origin ${{ secrets.url }}
            - run: git config --global user.email "jamal.alhneidi@gmail.com"
            - run: git config --global user.name "Jamal Alhneidi"
            - run: git status
            - run: git add .
            - run: git commit -m "tag parser auto commit"
            - run: git push origin HEAD:main
