name: tag-parser

on: push

jobs:
    tag-parser:
        name: Tag Parser
        runs-on: ubuntu-latest
        steps:
            - name: Tag Parser
              uses: cp-solutions-tag-parser@main