name: tag-parser

on:
    push:

jobs:
    tag-parser:
        name: Tag Parser
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo
              uses: actions/checkout@v4
            - name: Build
              run: |-
                  cd .github/actions/tag-parser
                  npm ci
                  npm run build
            - name: Parse solutions
              uses: ./.github/actions/tag-parser
            - name: Commit and push
              run: |-
                  git remote set-url origin ${{ secrets.url }}
                  git config --global user.email ${{ secrets.email }}
                  git config --global user.name ${{ secrets.name }}
                  git status
                  git add .
                  git commit -m "tag parser auto commit" || exit 0
                  git push origin HEAD:main
