name: tag-parser

on: push

jobs:
    tag-parser:
        name: Tag Parser
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Tag Parser
              uses: ./.github/actions/tag-parser
            - run: |
                  git config --global user.email "jamal.alhneidi@gmail.com"
                  git config --global user.name "Jamal Alhneidi"
            - run: git status
            - run: git add .
            - run: git commit -m "tag parser auto commit"
            - run: git push
