name: tag-parser

on: push

jobs:
    tag-parser:
        name: Tag Parser
        runs-on: ubuntu-latest
        steps:
            - name: Change directory
              run: cd tag-parser
            - name: Run parse
              run: npm run start
