name: tag-parser

on: push

jobs:
    tag-parser:
        name: Tag Parser
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Tag Parser
              uses: ./.github/actions/tag-parser